### ISSUE TITLE
Status of this document

### ISSUE THREAD

**Issue by Jxck** [explainers-by-googlers/standardizing-cross-site-cookie-semantics#7]
Hi Team

Thanks for working on this. I believe it's a very important missing piece for deprecating 3rd party cookie work.
I'm digging the behavior of [POST submit](https://github.com/DCtheTall/standardizing-cross-site-cookie-semantics?tab=readme-ov-file#top-level-cross-site-post-requests), and I accidentally found it in https://github.com/GoogleChromeLabs/privacy-sandbox-dev-support/issues/197 where @krgovind mentioned).

What is the current status of this document ? any progress for standardizing it ?
I understand this doc requires tons of works, but I think this document should be visible for more widely also.

Thanks
Jxck

**Comment by johannhof** [comment]
Hi @Jxck, the intent here is for this to become a WG Note by the [WebAppSec WG](https://www.w3.org/groups/wg/webappsec/), which will inform the ongoing [Cookie Layering](https://github.com/httpwg/http-extensions/issues/2084) efforts in standardizing this behavior across browsers.

We're making (slow) progress with all this, as you can imagine everyone on the Chrome side is very busy with the third-party cookie deprecation going on, so please stay tuned.
